// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyService.Infrastructure.Persistence;

#nullable disable

namespace PolicyService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    [Migration("20260907000012_AddPolicyCancellation")]
    partial class AddPolicyCancellation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PolicyService.Domain.Policies.Policy", b =>
                {
                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CancellationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasClaims")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Reference");

                    b.ToTable("Policies", (string)null);
                });

            modelBuilder.Entity("PolicyService.Domain.Policies.Policy", b =>
                {
                    b.OwnsOne("PolicyService.Domain.Policies.InsuredProperty", "Property", b1 =>
                        {
                            b1.Property<string>("PolicyReference")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressLine1");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressLine2");

                            b1.Property<string>("AddressLine3")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("AddressLine3");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("TEXT")
                                .HasColumnName("Postcode");

                            b1.HasKey("PolicyReference");

                            b1.ToTable("Policies");

                            b1.WithOwner()
                                .HasForeignKey("PolicyReference");
                        });

                    b.OwnsMany("PolicyService.Domain.Policies.Payment", "Payments", b1 =>
                        {
                            b1.Property<string>("PolicyReference")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Reference")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.HasKey("PolicyReference", "Reference");

                            b1.ToTable("Payments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PolicyReference");
                        });

                    b.OwnsMany("PolicyService.Domain.Policies.Policyholder", "Policyholders", b1 =>
                        {
                            b1.Property<string>("PolicyReference")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("PolicyReference", "Id");

                            b1.ToTable("Policyholders", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PolicyReference");
                        });

                    b.OwnsOne("PolicyService.Domain.Policies.Refund", "Refund", b1 =>
                        {
                            b1.Property<string>("PolicyReference")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Reference")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.HasKey("PolicyReference");

                            b1.ToTable("Refunds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PolicyReference");
                        });

                    b.Navigation("Payments");

                    b.Navigation("Policyholders");

                    b.Navigation("Property")
                        .IsRequired();

                    b.Navigation("Refund");
                });
#pragma warning restore 612, 618
        }
    }
}
